var model=[
  { 
  	'b_title':'北科大学子暑期实践走进乡村关注民生',
  	'b_src':[
            {'b_img':'images/img1.jpg'},
            {'b_img':'images/img2.jpg'},
            {'b_img':'images/img3.jpg'},
            {'b_img':'images/img4.jpg'},
            ],
  	'b_red':'推荐',
  	'b_time':'10小时前',
  	'b_comt':'831',
  	'listModel':[
  	            {
  		          'l_img':'images/img1.jpg',
  		          'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
  		          'l_red':'新闻',
  		          'l_time':'8小时前',
  		          'l_comt':'345'
             	},
             	{
  		          'l_img':'images/img2.jpg',
  		          'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
  		          'l_red':'新闻',
  		          'l_time':'8小时前',
  		          'l_comt':'345'
             	},
             	{
  		          'l_img':'images/img3.jpg',
  		          'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
  		          'l_red':'新闻',
  		          'l_time':'8小时前',
  		          'l_comt':'345'
             	},
             	{
  		          'l_img':'images/img4.jpg',
  		          'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
  		          'l_red':'新闻',
  		          'l_time':'8小时前',
  		          'l_comt':'345'
             	}
             ]
  },
   { 
    'b_title':'北科大学子暑期实践走进乡村关注民生',
    'b_src':[
            {'b_img':'images/list_banner1.jpg'}
            ],
    'b_red':'推荐',
    'b_time':'10小时前',
    'b_comt':'831',
    'listModel':[
                {
                'l_img':'images/img5.jpg',
                'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
                'l_red':'新闻',
                'l_time':'8小时前',
                'l_comt':'345'
              },
              {
                'l_img':'images/img6.jpg',
                'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
                'l_red':'新闻',
                'l_time':'8小时前',
                'l_comt':'345'
              },
              {
                'l_img':'images/img7.jpg',
                'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
                'l_red':'新闻',
                'l_time':'8小时前',
                'l_comt':'345'
              },
              {
                'l_img':'images/img8.jpg',
                'l_title':'习近平在第三届世界互联网大会讲话引起热烈反响',
                'l_red':'新闻',
                'l_time':'8小时前',
                'l_comt':'345'
              }
             ]
  }
]